# This file is auto-generated by scripts/setup.sh
# Do not edit manually — run: bash scripts/setup.sh

terraform {
  backend "s3" {
    # bucket  = "clickstream-tfstate-YOUR_ACCOUNT_ID"   ← filled by setup.sh
    # key     = "clickstream-pipeline/terraform.tfstate"
    # region  = "us-east-1"
    # encrypt = true
  }
}
