"""
Canonical clickstream event schema.

All events flowing through this pipeline conform to this schema — whether
they originate from the CSV, the Kinesis stream, or S3.
"""

import uuid
from datetime import UTC, datetime
from typing import Optional

import pandas as pd


class ClickstreamEvent:
    """
    Represents a single user interaction event.

    Fields:
        event_id:                  UUID generated by the simulator (not in original CSV)
        event_time:                Timestamp from the REES46 dataset
        arrival_time:              When the simulator actually published to Kinesis
        event_type:                'view', 'cart', or 'purchase'
        product_id:                Product identifier
        category_id:               Numeric category ID
        category_code:             Human-readable category path (nullable)
        brand:                     Brand name (nullable)
        price:                     Product price in USD
        user_id:                   User identifier
        session_id:                From REES46 user_session field
        is_late_arrival:           True if the injector delayed this event
        late_arrival_delay_seconds: How long the injector held it back (nullable)
    """

    VALID_EVENT_TYPES = {"view", "cart", "purchase"}

    def __init__(
        self,
        event_id: str,
        event_time: str,
        arrival_time: str,
        event_type: str,
        product_id: str,
        category_id: str | None,
        category_code: str | None,
        brand: str | None,
        price: float,
        user_id: str,
        session_id: str,
        is_late_arrival: bool = False,
        late_arrival_delay_seconds: int | None = None,
    ):
        self.event_id = event_id
        self.event_time = event_time
        self.arrival_time = arrival_time
        self.event_type = event_type
        self.product_id = str(product_id)
        self.category_id = str(category_id) if category_id else None
        self.category_code = category_code if pd.notna(category_code) else None
        self.brand = brand if pd.notna(brand) else None
        self.price = float(price) if price and pd.notna(price) else 0.0
        self.user_id = str(user_id)
        self.session_id = str(session_id)
        self.is_late_arrival = is_late_arrival
        self.late_arrival_delay_seconds = late_arrival_delay_seconds

    @classmethod
    def from_csv_row(cls, row: pd.Series) -> Optional["ClickstreamEvent"]:
        """
        Parse a REES46 CSV row into a ClickstreamEvent.
        Returns None if the row is malformed or has an unknown event_type.
        """
        try:
            event_type = str(row.get("event_type", "")).strip().lower()
            if event_type not in cls.VALID_EVENT_TYPES:
                return None

            now_iso = datetime.now(tz=UTC).isoformat()

            return cls(
                event_id=str(uuid.uuid4()),
                event_time=str(row["event_time"]),
                arrival_time=now_iso,
                event_type=event_type,
                product_id=row["product_id"],
                category_id=row.get("category_id"),
                category_code=row.get("category_code"),
                brand=row.get("brand"),
                price=row.get("price", 0.0),
                user_id=row["user_id"],
                session_id=row["user_session"],
            )
        except (KeyError, ValueError, TypeError):
            return None

    def to_dict(self) -> dict:
        """Serialise to a plain dict for Kinesis JSON encoding."""
        return {
            "event_id": self.event_id,
            "event_time": self.event_time,
            "arrival_time": self.arrival_time,
            "event_type": self.event_type,
            "product_id": self.product_id,
            "category_id": self.category_id,
            "category_code": self.category_code,
            "brand": self.brand,
            "price": self.price,
            "user_id": self.user_id,
            "session_id": self.session_id,
            "is_late_arrival": self.is_late_arrival,
            "late_arrival_delay_seconds": self.late_arrival_delay_seconds,
        }
